### ISSUE TITLE
关于获取全国人口迁移数据的问题

### ISSUE THREAD

**Issue by Cehnrro** [baisebaoma/baiduqianxi#1]
请问获取全国的人口迁徙数据的参数要如何设置,我根据您在注释中给出的例子设置如下参数却爬不出数据
![屏幕截图 2024-12-06 123606](https://github.com/user-attachments/assets/a6505283-44b8-4ea1-9f94-bdc8f500fc04)
![屏幕截图 2024-12-06 123644](https://github.com/user-attachments/assets/3feb65f9-3355-4ada-b735-4db2228d0c7d)

**Comment by baisebaoma** [comment]
[Cehnrro](https://github.com/Cehnrro) 您好，

我测试后似乎没有问题，详见截图，生成之文件均有内容。再试试？

<img width="1470" alt="image" src="https://github.com/user-attachments/assets/e563dc70-39e2-44fe-b9cb-4668c6e17281">

**Comment by Cehnrro** [comment]
感想回复,代码是可以正常运行的,但是不知道为何下载后存储数据的文件夹为空,即无内容
![屏幕截图 2024-12-06 153633](https://github.com/user-attachments/assets/175621e6-dbe1-402a-a077-a959f58af6cb)

![屏幕截图 2024-12-06 153444](https://github.com/user-attachments/assets/01a5b1d2-220d-4d23-a305-773252a8919c)

**Comment by baisebaoma** [comment]
我注意到了可能的问题所在：您使用的是 Jupyter Notebook 和 Windows，很有可能是因为代码实际运行的目录并不是 Notebook 文件保存的目录，所以使用相对路径无法保存到您希望的位置；

另外，在我的代码中我预期将这些文件保存在`./data/`下，所以这个是写死的，在`download_and_convert_jsonp`函数的`output_file`中将这个位置写死了。如果一定要修改存放的位置，也需要修改这里。

可能的的解决办法有：

1. 不使用 Jupyter Notebook，而使用原生 Python 运行。使用命令提示符打开`main.py`所在的文件夹，然后`python3 main.py`再试（可能需要提前切换到有对应库的环境或先安装这些库，如`requests`等）；
2. 修改上述两个位置，改为使用绝对路径（如"D:\\code\\Python\\c_data"）。

**Comment by Cehnrro** [comment]
问题已解决，果然是路径问题，非常非常感谢你🌹🌹🌹
